In [1]:
import requests
import pandas as pd
from pandas.io.json import json_normalize

In [2]:
pd.set_option('display.max_columns',None)

In [3]:
response = requests.get("https://fantasy.premierleague.com/api/bootstrap-static/")
players = response.json()['elements']
player_database = pd.DataFrame(players)

In [4]:
player_data = player_database[['id','first_name','second_name','element_type','form','now_cost',
                         'points_per_game','chance_of_playing_next_round','status','team','team_code','total_points',
                        'value_form','minutes','goals_scored','assists','clean_sheets','goals_conceded','own_goals',
                         'penalties_saved','penalties_missed','yellow_cards','red_cards','saves','bonus','bps',
                        'influence','creativity','threat','ict_index','influence_rank','influence_rank_type',
                        'creativity_rank','creativity_rank_type','threat_rank','threat_rank_type','ict_index_rank',
                        'ict_index_rank_type','corners_and_indirect_freekicks_order','direct_freekicks_order',
                         'penalties_order','event_points']]

In [5]:
player_data[['form','points_per_game','value_form','influence',
             'creativity','threat','ict_index']] = player_data[[
    'form','points_per_game','value_form','influence','creativity','threat','ict_index']].astype(float)

C:\Users\razi.majeed\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\frame.py:3069: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [6]:
player_data

,id,first_name,second_name,element_type,form,now_cost,points_per_game,chance_of_playing_next_round,status,team,team_code,total_points,value_form,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,direct_freekicks_order,penalties_order,event_points
0,1,Mesut,Ã–zil,3,0.0,68,0.0,0.0,n,1,3,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,614,247,614,247,614,247,614,247,NaN,NaN,NaN,0
1,2,Sokratis,Papastathopoulos,2,0.0,48,0.0,0.0,n,1,3,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,571,210,562,210,548,205,574,210,NaN,NaN,NaN,0
2,3,David,Luiz Moreira Marinho,2,0.3,54,1.1,75.0,d,1,3,9,0.1,479,0,0,0,9,0,0,0,0,0,0,0,70,99.4,25.8,40.0,16.5,252,95,291,91,251,75,291,95,NaN,4.0,NaN,0
3,4,Pierre-Emerick,Aubameyang,3,2.0,114,3.6,100.0,a,1,3,47,0.2,1166,3,1,3,16,1,0,0,2,0,0,4,146,186.6,201.2,372.0,76.0,141,51,65,45,30,16,40,25,NaN,NaN,1.0,0
4,5,CÃ©dric,Soares,2,0.1,46,1.0,100.0,a,1,3,1,0.0,5,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.0,0.0,0.0,558,206,546,206,527,199,561,206,NaN,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,563,Rayan,Ait Nouri,2,0.3,50,3.5,100.0,a,20,39,21,0.1,348,1,0,1,5,0,0,0,0,0,0,3,82,86.0,68.1,76.0,23.0,264,101,195,43,186,42,251,79,NaN,NaN,NaN,0
610,581,Owen,Otasowie,3,0.7,45,1.7,NaN,a,20,39,5,0.2,111,0,1,0,3,0,0,0,1,0,0,0,26,37.0,24.0,8.0,6.9,349,153,297,160,348,166,359,163,NaN,NaN,NaN,0
611,610,Theo,Corbeanu,3,0.0,45,0.0,NaN,a,20,39,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,552,216,540,217,521,209,555,216,NaN,NaN,NaN,0
612,611,Taylor,Perry,3,0.0,45,0.0,NaN,a,20,39,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,546,211,534,212,515,204,549,211,NaN,NaN,NaN,0
613,614,Luke,Cundle,3,0.0,45,0.0,NaN,a,20,39,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,550,215,538,216,519,208,553,215,NaN,NaN,NaN,0

In [15]:
#Player Database split
forwards = player_data[player_data['element_type'].isin([4])]
midfielders = player_data[player_data['element_type'].isin([3])]
defenders = player_data[player_data['element_type'].isin([2])]
goalkeepers = player_data[player_data['element_type'].isin([1])]

In [17]:
forwards.sample(10)

,id,first_name,second_name,element_type,form,now_cost,points_per_game,chance_of_playing_next_round,status,team,team_code,total_points,value_form,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,direct_freekicks_order,penalties_order,event_points
123,591,Max,Thompson,4,0.0,45,0.0,NaN,a,4,90,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,535,60,522,62,495,60,536,61,NaN,NaN,NaN,0
594,504,Fabio,Silva,4,0.5,52,1.0,NaN,a,20,39,4,0.1,52,0,0,0,3,0,0,0,0,0,0,0,8,3.2,13.7,46.0,6.1,399,46,288,41,181,41,325,42,NaN,NaN,NaN,0
516,358,Callum,Robinson,4,1.0,55,2.9,100.0,a,18,35,26,0.2,445,2,1,1,8,0,0,0,0,0,0,3,86,86.0,75.4,124.0,28.0,189,22,124,17,65,27,117,24,NaN,NaN,NaN,0
253,224,Jamie,Vardy,4,5.0,102,7.6,100.0,a,9,13,61,0.5,648,8,2,2,11,0,0,1,0,0,0,10,245,326.6,71.7,342.0,74.2,7,3,136,20,13,8,12,5,NaN,NaN,1.0,0
56,50,Keinan,Davis,4,0.0,43,1.0,75.0,d,2,7,1,0.0,28,0,0,0,0,0,0,0,0,0,0,0,3,4.4,12.9,6.0,2.3,390,44,294,42,311,48,375,47,NaN,NaN,NaN,0
124,592,Lewis,Richardson,4,0.0,45,0.0,NaN,a,4,90,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,534,59,521,61,494,59,535,60,NaN,NaN,NaN,0
593,476,Leonardo,Campana,4,0.0,48,0.0,NaN,a,20,39,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,560,66,551,68,537,67,561,67,NaN,NaN,NaN,0
139,118,Tammy,Abraham,4,5.5,72,4.5,NaN,a,5,8,36,0.8,467,3,2,3,5,0,0,0,0,0,0,5,125,154.2,103.9,284.0,54.4,71,12,80,7,21,13,32,14,NaN,NaN,NaN,0
446,359,Lys,Mousset,4,0.0,58,0.0,100.0,a,15,49,0,0.0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,592,71,592,73,592,73,594,73,NaN,NaN,NaN,0
103,87,Ashley,Barnes,4,1.0,60,1.8,100.0,a,4,90,9,0.2,381,0,0,2,7,0,0,0,1,0,0,0,5,20.2,78.0,117.0,21.4,339,36,121,16,68,28,167,28,NaN,NaN,1.0,0

In [21]:
forwards.nlargest(10,['form'])

,id,first_name,second_name,element_type,form,now_cost,points_per_game,chance_of_playing_next_round,status,team,team_code,total_points,value_form,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,direct_freekicks_order,penalties_order,event_points
197,164,Dominic,Calvert-Lewin,4,6.5,79,7.8,NaN,a,7,11,70,0.8,788,10,1,1,16,0,0,0,1,0,0,10,275,382.0,88.0,502.0,97.2,4,2,103,11,2,1,6,2,NaN,NaN,NaN,0
426,506,Callum,Wilson,4,6.5,65,7.4,100.0,a,14,4,67,1.0,787,7,3,3,11,0,0,0,1,0,0,13,236,284.0,101.1,319.0,70.2,9,4,86,9,16,10,13,6,NaN,NaN,1.0,12
61,514,Ollie,Watkins,4,5.5,61,6.1,NaN,a,2,7,49,0.9,720,6,1,4,11,0,0,0,0,0,0,6,188,269.6,142.5,344.0,75.6,11,6,44,3,12,7,10,4,NaN,NaN,3.0,0
139,118,Tammy,Abraham,4,5.5,72,4.5,NaN,a,5,8,36,0.8,467,3,2,3,5,0,0,0,0,0,0,5,125,154.2,103.9,284.0,54.4,71,12,80,7,21,13,32,14,NaN,NaN,NaN,0
253,224,Jamie,Vardy,4,5.0,102,7.6,100.0,a,9,13,61,0.5,648,8,2,2,11,0,0,1,0,0,0,10,245,326.6,71.7,342.0,74.2,7,3,136,20,13,8,12,5,NaN,NaN,1.0,0
138,117,Timo,Werner,4,4.8,95,5.3,100.0,a,5,8,48,0.5,770,4,3,4,9,0,0,0,0,0,0,5,185,212.2,114.4,354.0,68.1,30,8,69,6,10,6,15,7,NaN,NaN,1.0,0
472,377,Che,Adams,4,4.8,59,5.3,NaN,a,16,20,48,0.8,765,3,4,4,12,0,0,0,1,0,0,7,157,208.0,134.2,291.0,63.4,33,9,51,4,18,12,20,10,NaN,NaN,NaN,0
489,388,Harry,Kane,4,4.8,109,9.3,NaN,a,17,6,84,0.4,803,7,9,3,8,0,0,0,1,0,0,12,316,476.4,227.2,480.0,118.5,1,1,15,1,3,2,1,1,NaN,4.0,1.0,0
418,340,Joelinton CÃ¡ssio,ApolinÃ¡rio de Lira,4,3.5,57,2.3,NaN,a,14,4,21,0.6,487,1,1,1,8,0,0,0,2,0,0,2,79,102.4,82.7,115.0,30.0,168,19,110,15,69,29,104,23,NaN,NaN,NaN,11
167,140,Jordan,Ayew,4,3.2,57,3.0,100.0,a,6,31,24,0.6,584,1,1,2,9,0,0,0,0,0,0,2,62,71.8,37.7,134.0,24.4,211,25,205,31,57,25,146,26,NaN,NaN,4.0,2

In [23]:
midfielders.nlargest(10,['form'])

,id,first_name,second_name,element_type,form,now_cost,points_per_game,chance_of_playing_next_round,status,team,team_code,total_points,value_form,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,direct_freekicks_order,penalties_order,event_points
376,302,Bruno Miguel,Borges Fernandes,3,7.5,108,8.0,NaN,a,13,1,64,0.7,659,6,3,2,12,0,0,1,2,0,0,12,239,386.4,400.6,261.0,104.9,3,2,1,1,27,12,3,2,1.0,1.0,1.0,0
136,114,Hakim,Ziyech,3,7.0,83,6.0,100.0,a,5,8,30,0.8,275,1,3,2,2,0,0,0,0,0,0,6,97,112.4,149.7,37.0,30.0,152,52,38,29,205,108,105,59,1.0,NaN,NaN,0
43,37,Jack,Grealish,3,5.5,77,7.6,NaN,a,2,7,61,0.7,720,4,6,4,11,0,0,0,2,0,0,5,220,305.2,283.3,458.0,104.5,8,4,4,3,5,2,4,3,3.0,7.0,4.0,0
466,370,James,Ward-Prowse,3,5.5,60,5.0,100.0,a,16,20,45,0.9,810,3,1,4,13,0,0,0,1,0,0,6,195,232.4,212.5,71.0,51.6,24,8,18,13,130,73,37,19,1.0,1.0,2.0,0
257,228,Youri,Tielemans,3,5.0,64,4.0,NaN,a,9,13,36,0.8,810,3,0,3,12,0,0,0,3,0,0,3,165,223.0,95.6,101.0,41.9,25,9,94,62,83,45,54,31,2.0,2.0,3.0,0
328,468,Diogo,Jota,3,4.8,68,5.3,NaN,a,11,14,37,0.7,392,4,0,1,10,0,0,0,0,0,0,5,112,163.8,79.9,235.0,47.9,65,24,116,74,29,13,43,24,NaN,NaN,NaN,0
566,450,Pablo,Fornals,3,4.8,65,5.3,NaN,a,19,21,48,0.7,735,2,4,4,9,0,0,0,1,0,0,5,137,138.2,100.1,172.0,41.1,98,34,87,58,45,24,55,32,NaN,NaN,NaN,0
176,489,Eberechi,Eze,3,4.5,58,2.8,100.0,a,6,31,25,0.8,497,1,1,0,12,0,0,0,0,0,0,3,90,120.0,89.8,109.0,32.0,136,46,100,67,75,39,87,46,2.0,3.0,NaN,2
456,148,Theo,Walcott,3,4.5,58,4.8,100.0,a,16,20,24,0.8,369,1,3,1,8,0,0,0,0,0,0,0,65,88.0,75.2,113.0,27.7,186,71,125,79,73,37,120,67,NaN,NaN,NaN,0
317,254,Mohamed,Salah,3,4.2,122,8.4,100.0,a,11,14,67,0.3,719,8,1,1,16,0,0,0,0,0,0,7,220,349.8,282.7,551.0,118.3,5,3,5,4,1,1,2,1,NaN,2.0,2.0,0

In [16]:
print(str(len(forwards))+" "+str(len(midfielders))+" "+str(len(defenders))+" "+str(len(goalkeepers))+" ")

76 240 218 68